### ISSUE TITLE
[RFC][Feature Proposal] Use theme['$grid-breakpoints'] in JSX

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/bootstrap-styled#12]
We are missing one component like this one : 

https://github.com/dragma/styled-bootstrap-grid 

## Issue Type

- [x] Feature
## Description

This component will be wrapper with `withTheme` in order to access `theme['$grid-breakpoint']`.

This will permit to use media query within JSX.

## related issues

- #31 
- #12 
- #5

**Comment by santaclauze** [comment]
I don't think I see the difference between that library and our own components.

Do you mean something more like this?

https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/withWidth/withWidth.js ?

https://material-ui.com/layout/breakpoints/

This seems to also allow the implementation of https://github.com/bootstrap-styled/bootstrap-styled/issues/5 quite easily as well.
