### ISSUE TITLE
[Bug] Cannot use linear gradient

### ISSUE THREAD

**Issue by kopax** [bootstrap-styled/bootstrap-styled#13]
# bootstrap-styled

I've been trying to set a [linear-gradient](https://www.w3schools.com/css/css3_gradients.asp)

## Issue Type

- [x] Bug

## Description

Valid gradient values crash the rendering

![image](https://user-images.githubusercontent.com/1866564/48968792-49f53e80-f027-11e8-8d1d-eb893313e10c.png)

## Steps to reproduce

This is a valid linear gradient:

```css
background: #1e5799; /* Old browsers */
background: -moz-linear-gradient(-45deg, #1e5799 0%, #2989d8 50%, #207cca 51%, #7db9e8 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(-45deg, #1e5799 0%,#2989d8 50%,#207cca 51%,#7db9e8 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(135deg, #1e5799 0%,#2989d8 50%,#207cca 51%,#7db9e8 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#1e5799', endColorstr='#7db9e8',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
```

This is how I have set my gradient:

```js
const theme = makeTheme({
  '$btn-primary-bg': 'linear-gradient(#B21255, #790A68)',
});
```

Produce the following error

# Versions

- Node/NPM: 11/6
- bootstrap-styled: 2.0.4

**Comment by santaclauze** [comment]
Question is now:

**Q**. should we also add these new variables to [bootstrap-styled](https://github.com/bootstrap-styled/bootstrap-styled)?

**Thoughts:** This creates a greater dependency between each. We will have to update both each time we add features to ou v4 library. However v4 is supposed to reflect bootstrap so it seems that we are deviating from out goal.

**Suggestion:**  

1. Should we then take the leap and say that [bootstrap-styled](https://github.com/bootstrap-styled/bootstrap-styled) is ONLY all the variables of bootstrap + theming methods. That will remain unchanged for larger length of time. 

1. Treat [v4](https://github.com/bootstrap-styled/v4) like an extension of bootstrap with additional features and only add the new variables with their individual makeThemes.

1. Think of adding the `box-shadow` as a [css-utils](https://github.com/bootstrap-styled/css-utils) in the [BootstrapProvider](https://github.com/bootstrap-styled/provider) so it can be applied globally.

**Thoughts:** This well allow us to keep the same discourse regarding [bootstrap-styled](https://github.com/bootstrap-styled/bootstrap-styled) without any ambiguity. [v4](https://github.com/bootstrap-styled/v4) becomes a better than bootstrap's library. Finally adding the `box-shadow` to `css-utils` would enable quick box-shadowing across the application.
