### ISSUE TITLE
Override colors and brands value is not working

### ISSUE THREAD

**Issue by Mehran91z** [bootstrap-styled/bootstrap-styled#144]
# bootstrap-styled

There is a problem with changing theme variables at same time, changing these two variables not working:
```
{
  '$brand-danger': 'green',
  '$green': '#FFF',
}
```

## Issue Type

- [ ] Bug

## Steps to reproduce

01. Import `BootstrapProvider` to `_app.js`
02. Inject `theme` custom config to this provider:
```
<Provider store={store}>
  <BootstrapProvider theme={myTheme}>
          <ResetStyledComponent />
          <Component {...pageProps} />
  </BootstrapProvider>
</Provider>
```
03. Add the following config object to myTheme:
```
const myTheme = {
  '$brand-danger': 'green',
  '$green': '#FFF'
};
```
04. Add Button component to app
`<Button color={'danger'}>Click</Button>`

04. Run the app

## Expected

It should change color of **danger buttons** to white, but there is green color still there. 

## Tested Things
I've test it with `makeTheme` function but the problem still exists:
```
const makedTheme = makeTheme(myTheme);
  <BootstrapProvider theme={makedTheme}>
          <ResetStyledComponent />
          <Component {...pageProps} />
  </BootstrapProvider>

```
## Suggestions
I think the problem is because of `'$brand-danger': 'green'` config in theme object that changes v['green'] to just 'green', so changing '$green' after that not working.
So if we could set `'$brand-danger'` to `$green` or `v['green']` maybe this problem would be resolved.

# Versions

- Node/NPM: v13.0.1/6.12.0
- OS: Windows 10
- bootstrap-styled: 2.7.2

**Comment by kopax** [comment]
Hi and thanks for using bootstrap-styled, looking at your configuration:

```jsx
const myTheme = {
  '$brand-danger': 'green',
  '$green': '#FFF'
};
```

This explicitly state that `$brand-danger` value is `green`.

If you want to process your theme using the bootstrap v4 logic, you must read the logic provided by our `makeTheme` to understand what values will be set in your theme. 

If you do not want to use bootstrap 4 logic, I would recommend you not to use our `makeTheme`, which is by default called in `<BootstrapProvider />`.

Iinstead, use `theme` and override your values one by one (you will lose all the logic` of the makeTheme`) and use the `<ThemeProvider />` from `styled-components` instead.

You have the full control on the theme at all point.

If you feel that this doesn't cover your problem or that it doesn't answer the question, feel free to reply and add more details to your question.

**Comment by Mehran91z** [comment]
@kopax Hi and thank you for your answer, I want to use bootstrap v4 logic with your package, and I need to change `$brand-danger` to another variable (like `$green`) and change `$green` to some green color (like #0f0).

So how can do it with `makeTheme`?
I need something like this:
```
const theme = {
  '$green': '#0F0',
  '$brand-danger': '$green',
}
```

Could you please help me with this `makeThme` method? Kind of it's not well [documented](https://bootstrap-styled.github.io/bootstrap-styled/#/Themes).
And I did it so far but nothing happens:
```
const myTheme = makeTheme(v => {
  v['$green'] = '#0F0';
  v['$brand-danger'] = v['$green'];
  return v;
});
```

**Comment by kopax** [comment]
You need to understand the logic behind it. You can't passe variable name on the right side of your theme object. You can only pass values. (That's why it work when you assign a value first and read from that  variable).

The makeTheme can compute for your most of the variable **with bootstrap 4** logic of variable computation. If you need another logic you need to write your own makeTheme.

If you want the bootstrap 4 logic. Then you must read what's a ternary operator and see the order of variable assignation in the makeTheme in order to leverage the computation for the right variable at the right moment. 

From what I see you need to get some basic js knowledge to understand it, such as how work ternary operator.
